if [ -f ~/.localrc.before ]; then
    . ~/.localrc.before
fi

if [[ ${PROFILE_ZSH:0} -eq 1 ]]; then zmodload zsh/zprof; fi

export ZSH_HOME="${HOME}/.config/zsh"

source "${ZSH_HOME}/antigen.zsh"
antigen init "${ZSH_HOME}/antigenrc"

if [ -f ${HOME}/.localrc ]; then
    source ${HOME}/.localrc
fi

if [[ ${PROFILE_ZSH} -eq 1 ]]; then zprof; fi