#!/bin/bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# startup scripts
xsetroot -solid '#262626'
picom &
xset r rate 200 45

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Super    # Use super as the main modifier

hc keybind $Mod-q close
hc keybind $Mod-Shift-r reload
hc keybind $Mod-space spawn rofi -show run
hc keybind $Mod-Return spawn alacritty

hc keybind Ctrl-Shift-space spawn dunstctl close-all

# audio
hc keybind XF86AudioRaiseVolume spawn amixer -q sset Master 5%+ unmute
hc keybind XF86AudioLowerVolume spawn amixer -q sset Master 5%- unmute
hc keybind XF86AudioMute spawn amixer -q sset Master toggle

# display
hc keybind XF86MonBrightnessUp spawn xbacklight +15
hc keybind XF86MonBrightnessDown spawn xbacklight -15

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left    focus left
hc keybind $Mod-Down    focus down
hc keybind $Mod-Up      focus up
hc keybind $Mod-Right   focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left      shift --level=tabs left
hc keybind $Mod-Shift-Down      shift --level=tabs down
hc keybind $Mod-Shift-Up        shift --level=tabs up
hc keybind $Mod-Shift-Right     shift --level=tabs right

# tab movement
hc keybind $Mod-Ctrl-Next   focus --level=tabs right
hc keybind $Mod-Ctrl-Prior  focus --level=tabs left

# explode the current frame
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    tag="${tag_names[$i]}"
    hc add "$tag"
    hc keybind "$Mod-$tag" use_index "$i"
    hc keybind "$Mod-Shift-$tag" move_index "$i"
    # load default layout on all tags but the first
    if [[ "$tag" -ne 1 ]]; then
        if [[ $(hc attr tags.by-name.$tag.client_count) -eq 0 ]]; then
            hc load "$tag" "$(cat "$HOME/.config/herbstluftwm/layout/workhorse")"
        fi
    fi
done

hc set swap_monitors_to_get_tag 0

# layouting
hc keybind $Mod-z spawn select-layout
hc keybind $Mod-x remove
# hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-space set_attr clients.focus.floating toggle
# hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-c cycle_layout 1 vertical horizontal max

# mouse
hc mouseunbind --all
hc mousebind Ctrl-Shift-Button1 move
hc mousebind Ctrl-Shift-Button3 zoom

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#585987'
hc set frame_border_width 1
hc set frame_bg_transparent on
hc set frame_transparent_width 4

hc set always_show_frame false
hc set frame_gap 4
hc set frame_padding 0
hc set window_gap 0

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color '#ffa500'
hc attr theme.inner_width 2
hc attr theme.inner_color black
hc attr theme.border_width 4
hc attr theme.floating.border_width 5
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#9fbc00'
hc attr theme.background_color '#2b2d31'
hc attr theme.title_color 'white'
hc attr theme.active.title_color 'black'
hc attr theme.title_height 17
hc attr theme.title_depth 6
hc attr theme.title_when multiple_tabs

hc set smart_window_surroundings false
hc set smart_frame_surroundings true
hc set mouse_recenter_gap 0
hc set tabbed_max true

# rules
hc unrule -F

# focus new clients
hc rule focus=on
# try to place floats non-overlapping by default
hc rule floatplacement=smart

# reminder: use xprop to lookup window details

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class=Kazam floating=on

# always float certain apps
hc rule class=Pavucontrol floating=on floatplacement=center
hc rule class=Blueman-manager floating=on floatplacement=center

hc rule class=Steam floating=on floatplacement=center
hc rule name=Steam floating=on floatplacement=center
hc rule class~"steam_app.*" floating=on floatplacement=center
hc rule class="steam" floating=on floatplacement=center

hc rule fixedsize floating=on floatplacement=smart

# zoom
hc rule class='zoom' floating=on floatplacement=smart

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# load monitors
hc detect_monitors

# run polybar
~/.config/herbstluftwm/panel.sh

# set wallpaper
~/.config/herbstluftwm/wallpaper.sh
